package src;

import src.types.*;

public interface 
{
    
	public void setUp(String testcaseName);
	public void tearDown(String testcaseName);
	public void sleep(double time);
	public void log(String m);
	/** communication functions for  url interface */
	public void performnullenter_URL_Action(nullenter_URL_Action argnullenter_URL_Action);

	public void performnullClick_Transaction_Action(nullClick_Transaction_Action argnullClick_Transaction_Action);

	/** GUI verification functions */
	public void verifynullParabank_Welcome_screen(nullParabank_Welcome_screen argnullParabank_Welcome_screen);

	public void verifynullAccount_Services_screen(nullAccount_Services_screen argnullAccount_Services_screen);

	public void verifynullBill_Payment_Service_screen(nullBill_Payment_Service_screen argnullBill_Payment_Service_screen);

	public void verifynullOpen_New_Account_screen(nullOpen_New_Account_screen argnullOpen_New_Account_screen);

	public void verifynullApply_for_a_Loan_screen(nullApply_for_a_Loan_screen argnullApply_for_a_Loan_screen);

	public void verifynullAdministration_screen(nullAdministration_screen argnullAdministration_screen);

	public void verifynullForgot_Login_info_screen(nullForgot_Login_info_screen argnullForgot_Login_info_screen);

	public void verifynullFind_Transactions_screen(nullFind_Transactions_screen argnullFind_Transactions_screen);

	public void verifynullTransaction_Result_screen(nullTransaction_Result_screen argnullTransaction_Result_screen);

	public void verifynullRegister_screen(nullRegister_screen argnullRegister_screen);

	public void verifynullTransfer_Funds_screen(nullTransfer_Funds_screen argnullTransfer_Funds_screen);

	public void verifynullUpdate_Profile_screen(nullUpdate_Profile_screen argnullUpdate_Profile_screen);

	/** GUI input functions  */
	public void fillnullFill__Parabank_Welcome_screen(nullFill__Parabank_Welcome_screen argnullFill__Parabank_Welcome_screen);

	public void clicknullLOG_IN_button_Parabank_Welcome_screen_Customer_Login_form(nullLOG_IN_button_Parabank_Welcome_screen_Customer_Login_form argnullLOG_IN_button_Parabank_Welcome_screen_Customer_Login_form);

	public void verifynullAccounts_Overview_Action(nullAccounts_Overview_Action argnullAccounts_Overview_Action);

	public void clicknullBill_Pay_hyperlink_Account_Services_screen(nullBill_Pay_hyperlink_Account_Services_screen argnullBill_Pay_hyperlink_Account_Services_screen);

	public void fillnullFill__Bill_Payment_Service_screen(nullFill__Bill_Payment_Service_screen argnullFill__Bill_Payment_Service_screen);

	public void verifynullBill_Payment_Complete_Action(nullBill_Payment_Complete_Action argnullBill_Payment_Complete_Action);

	public void clicknullOpen_New_Account_hyperlink_Account_Services_screen(nullOpen_New_Account_hyperlink_Account_Services_screen argnullOpen_New_Account_hyperlink_Account_Services_screen);

	public void fillnullFill__Open_New_Account_screen(nullFill__Open_New_Account_screen argnullFill__Open_New_Account_screen);

	public void clicknullOpen_New_Account_button_Open_New_Account_screen(nullOpen_New_Account_button_Open_New_Account_screen argnullOpen_New_Account_button_Open_New_Account_screen);

	public void verifynullNew_Account_Action(nullNew_Account_Action argnullNew_Account_Action);

	public void clicknullAccount_Overview_hyperlink_Open_New_Account_screen(nullAccount_Overview_hyperlink_Open_New_Account_screen argnullAccount_Overview_hyperlink_Open_New_Account_screen);

	public void verifynullAccount_Overviews_Action(nullAccount_Overviews_Action argnullAccount_Overviews_Action);

	public void clicknullRequest_Loan_hyperlink_Account_Services_screen(nullRequest_Loan_hyperlink_Account_Services_screen argnullRequest_Loan_hyperlink_Account_Services_screen);

	public void fillnullFill__Apply_for_a_Loan_screen(nullFill__Apply_for_a_Loan_screen argnullFill__Apply_for_a_Loan_screen);

	public void clicknullApply_Now_button_Apply_for_a_Loan_screen(nullApply_Now_button_Apply_for_a_Loan_screen argnullApply_Now_button_Apply_for_a_Loan_screen);

	public void verifynullLoan_Request_Processed_Action(nullLoan_Request_Processed_Action argnullLoan_Request_Processed_Action);

	public void clicknullAccount_Overview_hyperlink_Apply_for_a_Loan_screen(nullAccount_Overview_hyperlink_Apply_for_a_Loan_screen argnullAccount_Overview_hyperlink_Apply_for_a_Loan_screen);

	public void verifynullAccount_Overviews_for_Loan_Action(nullAccount_Overviews_for_Loan_Action argnullAccount_Overviews_for_Loan_Action);

	public void clicknullAdmin_Page_hyperlink_Parabank_Welcome_screen(nullAdmin_Page_hyperlink_Parabank_Welcome_screen argnullAdmin_Page_hyperlink_Parabank_Welcome_screen);

	public void fillnullFill__Administration_screen(nullFill__Administration_screen argnullFill__Administration_screen);

	public void clicknullSUBMIT_button_Administration_screen(nullSUBMIT_button_Administration_screen argnullSUBMIT_button_Administration_screen);

	public void verifynullTransaction_Error__Action(nullTransaction_Error__Action argnullTransaction_Error__Action);

	public void clicknullForgot_login_info__hyperlink_Parabank_Welcome_screen_Customer_Login_form(nullForgot_login_info__hyperlink_Parabank_Welcome_screen_Customer_Login_form argnullForgot_login_info__hyperlink_Parabank_Welcome_screen_Customer_Login_form);

	public void fillnullFill__Forgot_Login_info_screen(nullFill__Forgot_Login_info_screen argnullFill__Forgot_Login_info_screen);

	public void clicknullFIND_MY_LOGIN_INFO_button_Forgot_Login_info_screen_Forgot_Login_info_form(nullFIND_MY_LOGIN_INFO_button_Forgot_Login_info_screen_Forgot_Login_info_form argnullFIND_MY_LOGIN_INFO_button_Forgot_Login_info_screen_Forgot_Login_info_form);

	public void clicknullFind_Transactions_hyperlink_Account_Services_screen(nullFind_Transactions_hyperlink_Account_Services_screen argnullFind_Transactions_hyperlink_Account_Services_screen);

	public void fillnullFill__Find_Transactions_screen(nullFill__Find_Transactions_screen argnullFill__Find_Transactions_screen);

	public void clicknullFind_Transactions_button_Find_Transactions_screen_Date_Range_form(nullFind_Transactions_button_Find_Transactions_screen_Date_Range_form argnullFind_Transactions_button_Find_Transactions_screen_Date_Range_form);

	public void clicknullFind_Transactions_button_Find_Transactions_screen_Transaction_ID_form(nullFind_Transactions_button_Find_Transactions_screen_Transaction_ID_form argnullFind_Transactions_button_Find_Transactions_screen_Transaction_ID_form);

	public void verifynullTransaction_Details_Action(nullTransaction_Details_Action argnullTransaction_Details_Action);

	public void clicknullAccount_Overview_hyperlink_Account_Services_screen(nullAccount_Overview_hyperlink_Account_Services_screen argnullAccount_Overview_hyperlink_Account_Services_screen);

	public void clicknullFind_Transactions_button_Find_Transactions_screen_Transaction_By_Date_form(nullFind_Transactions_button_Find_Transactions_screen_Transaction_By_Date_form argnullFind_Transactions_button_Find_Transactions_screen_Transaction_By_Date_form);

	public void verifynullInvalid_Credentials_Action(nullInvalid_Credentials_Action argnullInvalid_Credentials_Action);

	public void clicknullRegister_hyperlink_Parabank_Welcome_screen_Customer_Login_form(nullRegister_hyperlink_Parabank_Welcome_screen_Customer_Login_form argnullRegister_hyperlink_Parabank_Welcome_screen_Customer_Login_form);

	public void fillnullFill__Register_screen(nullFill__Register_screen argnullFill__Register_screen);

	public void clicknullRIGISTER_button_Register_screen_Signup_form(nullRIGISTER_button_Register_screen_Signup_form argnullRIGISTER_button_Register_screen_Signup_form);

	public void verifynullInvalid_Register_Action(nullInvalid_Register_Action argnullInvalid_Register_Action);

	public void verifynullAccount_Created_Action(nullAccount_Created_Action argnullAccount_Created_Action);

	public void verifynullReject_Register_Action(nullReject_Register_Action argnullReject_Register_Action);

	public void clicknullTransfer_Funds_hyperlink_Account_Services_screen(nullTransfer_Funds_hyperlink_Account_Services_screen argnullTransfer_Funds_hyperlink_Account_Services_screen);

	public void fillnullFill__Transfer_Funds_screen(nullFill__Transfer_Funds_screen argnullFill__Transfer_Funds_screen);

	public void clicknullTRANSFER_button_Transfer_Funds_screen(nullTRANSFER_button_Transfer_Funds_screen argnullTRANSFER_button_Transfer_Funds_screen);

	public void clicknullFind_Transactions_button_Find_Transactions_screen_Find_By_Amount_form(nullFind_Transactions_button_Find_Transactions_screen_Find_By_Amount_form argnullFind_Transactions_button_Find_Transactions_screen_Find_By_Amount_form);

	public void clicknullUpdate_Contact_Info_hyperlink_Account_Services_screen(nullUpdate_Contact_Info_hyperlink_Account_Services_screen argnullUpdate_Contact_Info_hyperlink_Account_Services_screen);

	public void fillnullFill__Update_Profile_screen(nullFill__Update_Profile_screen argnullFill__Update_Profile_screen);

	public void clicknullUPDATE_PROFILE_button_Update_Profile_screen(nullUPDATE_PROFILE_button_Update_Profile_screen argnullUPDATE_PROFILE_button_Update_Profile_screen);

	public void verifynullProfile_Updated_Action(nullProfile_Updated_Action argnullProfile_Updated_Action);

	public void clicknullLog_Out_hyperlink_Account_Services_screen(nullLog_Out_hyperlink_Account_Services_screen argnullLog_Out_hyperlink_Account_Services_screen);

}
